### ISSUE TITLE
Container image misses git

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/peribolos-syncer#15]
**Describe the bug**

The go git client uses `git` `os.Exec` under the hood, but `git` is missing from the container image now built with `ko`.

**How to reproduce it**

For example in a Pod:

```yml
[...]
    spec:
      containers:
      - image: ghcr.io/falcosecurity/peribolos-syncer:0.2.0
        command:
        - peribolos-syncer
        args:
        - sync
        - github
        - --org=falcosecurity
        - --team=evolution-maintainers
        - --peribolos-config-path=config/org.yaml
        - --peribolos-config-repository=test-infra
        - --peribolos-config-git-ref=master
        - --owners-repository=evolution
        - --owners-git-ref=main
        - --approvers-only=true
        - --git-author-name=poiana
        - --git-author-email="51138685+poiana@users.noreply.github.com"
        - --gpg-public-key=/tmp/gpg-pub/poiana.pub
        - --gpg-private-key=/tmp/gpg/poiana.asc
        - --github-username=poiana
        - --github-endpoint=http://ghproxy.default.svc.cluster.local
        - --github-endpoint=https://api.github.com
        - --github-hourly-tokens=1200
        - --github-token-path=/etc/github-token/oauth
```

**Expected behaviour**

To execute git commands.

**Logs**

```
Error: error building git client gitclientfactory: error creating git client: Error getting git client: exec: "git": executable file not found in $PATH
```

**Environment**

NA

**Additional context**

NA
